name: Unity - Automated Build
on:
  workflow_dispatch:
  push:
    branches:
      - build
    paths:
      - 'Assets/**/*'
      - 'Packages/**/*'
      - 'ProjectSettings/**/*'
      - .github/workflows/main.yml

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # cancel if a new push is made

permissions:
  actions: read
  pull-requests: write
  checks: write
  id-token: write
  contents: write

jobs:
  # ----- Build for WebGL -----
  buildWebGL:
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      #- run: git submodule update --init --recursive

      - name: Restore Library cache
        uses: actions/cache@v4.0.2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: MeetTheRookie

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Build-WebGL
          path: build
          if-no-files-found: warn

  # ----- Build for Windows -----
  buildWindows:
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      #- run: git submodule update --init --recursive

      - name: Restore Library cache
        uses: actions/cache@v4.0.2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: MeetTheRookie

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Build-Windows
          path: build
          if-no-files-found: warn

  # ----- Deploy to Github Pages -----
  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4.1.4
        with:
          ref: gh-pages

      - name: Download WebGL build artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: Build-WebGL
          path: build

      - name: Copy WebGL build to gh-pages
        run: |
          mkdir -p ./Build-WebGL
          cp -r build/* ./Build-WebGL

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Update WebGL build"
          git push origin gh-pages
