name: Unity - Automated Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Assets/**/*'
      - 'Packages/**/*'
      - 'ProjectSettings/**/*'
      - .github/workflows/main.yml

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # cancel if a new push is made
      
permissions:
  actions: read
  pull-requests: write
  checks: write
  id-token: write
  contents: write

jobs:
  # ----- Build for WebGL -----
  buildWebGL:
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - run: git submodule update --init --recursive

      - name: Restore Library cache
        uses: actions/cache@v4.0.2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: MeetTheRookie

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: build-WebGL
          path: build/WebGL

  # ----- Build for Windows -----
  buildWindows:
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - run: git submodule update --init --recursive

      - name: Restore Library cache
        uses: actions/cache@v4.0.2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: MeetTheRookie

      - uses: actions/download-artifact@v4.1.7
        with:
          name: build-WebGL
          path: build/WebGL


  # ----- Deploy to Github Pages -----  
  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      - uses: actions/download-artifact@v4.1.7
        with:
          name: build-WebGL
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL